---
################
#### RouterOS ###
#################
- name: Config switch huawei
  hosts: huawei
  connection: local
  vars:      
    cli:
      host:  "{{ ansible_host }}"
      port: "{{ ansible_ssh_port }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_ssh_pass }}"
  tasks:
  - name: Configure loghost
    ce_command:
      commands: 
        - system-view
        -  info-center loghost ipServidor port 5000
      provider: "{{ cli }}"